### PR TITLE
JSON payload support

### LINKED ISSUE #18: Support Other Graphql Query Formats
I have found alot of graphql servers take queries via post requests differently.

`{ "query": "{}", "variables": {} }`

This is the format that Shopify's graphql server supports. It has to be made as a post request to the /graphql endpoint. Would it be possible to support this query format?

### PR DESCRIPTION
**Pull request by orangecms**
resolves #18

### CODE REVIEW

**Comment by jessesomerville** [comment]
Any update on merging this into master?

**Comment by orangecms** [comment]
> Any update on merging this into master?

Maybe upstream is no longer interested in or watching the project; let's create a fork if that works for you. :)

**Comment by jessesomerville** [comment]
I actually just decided to start fresh with a new project that has better CI/CD integration and extensibility for plugin management using a scanner class and a plugin interface of some sort.  Once I get it to a decent starting point I can rope you in on it if you are interested :)

**Comment by ip-rw** [comment]
How much scope you think this tool has? Merge it...

**Pull request merged**
